"""add reset token to users

Revision ID: fc21527413f2
Revises: dcaf76f81111
Create Date: 2026-02-27 23:46:18.781592

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "fc21527413f2"
down_revision = "dcaf76f81111"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("reset_token", sa.String(length=255), nullable=True)
        )
        batch_op.add_column(
            sa.Column("reset_token_expires_at", sa.DateTime(), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("reset_token_expires_at")
        batch_op.drop_column("reset_token")

    # ### end Alembic commands ###
